
name: Truffle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Show NodeJS version    
      run: node -v
      
    - name: Show Yarn version    
      run: yarn --version
    
#    - name: Install Truffle
#      run: npm install truffle -g
    
#    - name: Install Truffle Dependencies
#      run: npm install      
   
#     - name: Increase memory allocation
#       run: export NODE_OPTIONS="--max-old-space-size=8192"
      
#     - name: check memory allocation
#       run: node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))'
   
#     - name: Run Truffle Test
#       run: truffle test --max-old-space-size=8192
    
#    - name: Run Test Coverage
#      run: truffle run coverage
